name: golang-pipeline
on: push
jobs:
  test:
    name: Check errors and run tests
    runs-on: ubuntu-latest
    container: golang:1.21.3
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...